name: Web3ExplorerWs CD
on:
    push:
      branches:
        - main
env:
    node-version: 20.11.1

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.6
        run: |
          if gh release view "$tag" --repo="$GITHUB_REPOSITORY" &> /dev/null; then
            echo "Release $tag already exists."
          else
            # Create the release if it does not exist
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes
            echo "Release $tag created."
          fi

  desktop-build:
    name: desktop-build
    runs-on: ubuntu-22.04
    needs: release
    env:
      tag: v1.0.6
      RELEASE_URL: https://github.com/${{github.repository}}/releases/tag/${tag#v}
    steps:
      - name: echo release_url
        run: |
          echo "Generated Release URL: ${{ RELEASE_URL }}"
